/**
 * File: NvsPatcher.c
 * Author: Matthew Millman
 *
 * Work in progress
 * 
 * SPDX-License-Identifier: BSD-2-Clause-Patent
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.
 * 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "NvsPatcher.h"

#define SRLD_OFFSET   0x7A7

typedef struct _EFI_GLOBAL_NVS_AREA_PROTOCOL
{
  VOID *Area;
} EFI_GLOBAL_NVS_AREA_PROTOCOL;

// 481E4E07-3281-A147-8C2C-3F14AD9A66DC
//EFI_GUID gEfiGlobalNvsAreaProtocolGuid = { 0x74e1e48, 0x8132, 0x47a1, { 0x8c, 0x2c, 0x3f, 0x14, 0xad, 0x9a, 0x66, 0xdc }};

EFI_STATUS EFIAPI UefiMain(IN EFI_HANDLE ImageHandle, IN EFI_SYSTEM_TABLE *SystemTable)
{
  EFI_STATUS Status;
  EFI_GLOBAL_NVS_AREA_PROTOCOL  *GlobalNvsArea;

  SerialPortInitialize();

  DEBUG((DEBUG_INFO, "NvsPatcher: Starting Up"));
  
  Status = gBS->LocateProtocol (
                  &gEfiGlobalNvsAreaProtocolGuid,
                  NULL,
                  (VOID **)&GlobalNvsArea
                  );

  ASSERT_EFI_ERROR(Status);

  *(UINT8 *)(GlobalNvsArea->Area + SRLD_OFFSET) = 0x01; // SRLD

  DEBUG((DEBUG_INFO, "GlobalNvsArea: %p SRLD: 0x%02X\n", GlobalNvsArea->Area, *(UINT8 *)(GlobalNvsArea->Area + SRLD_OFFSET)));

  return Status;
}
